Hooks:Add("LocalizationManagerPostInit", "Perk Deck Fixes Localization", function(loc)
	LocalizationManager:add_localized_strings({
        -- ["menu_deck8_3_desc"] = "When you are within medium range of an enemy, you receive an additional ##8%## less damage from enemies.\n\nThe OVERDOG melee buff duration is increased by ##6## seconds.",
		["menu_deck13_5_desc"] = "Increases the maximum health that can be stored by ##50%##.\n\nYou gain ##10%## more health.\n\nYour chance to dodge is increased by ##15%##.",
		["menu_deck15_9_desc"] = "Dealing damage will grant you ##30## armor - this can only occur once every ##1.5## seconds.\n\nDeck Completion Bonus: Your chance of getting a higher quality item during a PAYDAY is increased by ##10%##.",
		["menu_deck17_1_desc"] = "Unlocks and equips the Kingpin Injector.\n\nWhile in game you can use the throwable key to activate the Injector. Activating the Injector will heal you with ##75%## of all damage taken for ##6## seconds.\n\nYou can still take damage during the effect. The Injector can only be used once every ##30## seconds. The cooldown is reduced by ##1## second per enemy killed.",
		-- ["menu_deck17_9_desc"] = "You gain ##40%## more health.\n\nFor every ##50## points of health gained during the Injector effect while at maximum health, the recharge time of the injector is reduced by ##1## second.\n\nDeck Completion Bonus: Your chance of getting a higher quality item during a PAYDAY is increased by ##10%##.",
		["menu_deck19_1_desc"] = "Unlocks and equips the Stoic's Hip Flask.\n\nDamage is now reduced by ##75%##. The remaining damage will be applied directly.\n\nThe ##75%## reduced damage will be applied over-time (##12## seconds) instead.\n\nYou can use the throwable key to activate the Stoic Hip Flask and immediately negate any pending damage. The flask has a ##10## second cooldown but time remaining will be lessened by ##1## second per enemy killed.",
		["menu_deck20_1_desc"] = "Unlocks and equips the Gas Dispenser.\n\nTo activate the Gas Dispenser you need to look at another allied unit within a ##18## meter radius with clear line of sight and press the throwable key to tag them.\n\nEach enemy you or the tagged unit kills will now heal you for ##15## health and the tagged unit for ##7.5## health./n/nEach enemy you kill will now extend the duration by ##1.3## seconds and reduce the cooldown timer by ##2## seconds.\n\nThe effect will last for a duration of ##12## seconds and has a cooldown of ##60## seconds.",
		["menu_deck21_5_desc"] = "Killing an enemy while the feedback effect is active will regenerate ##20## health.\n\nYour chance to dodge is increased by ##15%##.",
		["menu_deck21_9_desc"] = "Crew members killing enemies while the feedback effect is active will regenerate ##10## health.\n\nYour chance to dodge is increased by an additional ##15%##.\n\nDeck Completion Bonus: Your chance of getting a higher quality item during a PAYDAY is increased by ##10%##."
		
		})
end)